name       : texworks
version    : 0.6.2
release    : 6
source     :
    - https://github.com/TeXworks/texworks/archive/release-0.6.2.tar.gz : 22885c11d92654b0cba1f4808fc9aa3c2fdd3e5435fd89dff9aa1e67658a6339
license    : GPL-2.0
component  : editor
summary    : A simple TeX front-end program
description: |
    A simple TeX front-end program
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(hunspell)
    - pkgconfig(poppler)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Script)
rundeps    :
    - texlive
setup      : |
    %cmake -DDESIRED_QT_VERSION=5 .
build      : |
    %make
install    : |
    %make_install
