name       : texworks
version    : 0.6.3
release    : 10
source     :
    - https://github.com/TeXworks/texworks/archive/release-0.6.3.tar.gz : b4695539b9666935d2c467cc618c7d79c174e2ec728e31f72df8534862a5c290
homepage   : http://www.tug.org/texworks/
license    : GPL-2.0-or-later
component  : editor
summary    : A simple TeX front-end program
description: |
    TeXworks is an environment for authoring TeX (LaTeX, ConTeXt, etc) documents, with a Unicode-based, TeX-aware editor, integrated PDF viewer, and a clean, simple interface accessible to casual and non-technical users.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Script)
    - pkgconfig(dbus-1)
    - pkgconfig(hunspell)
    - pkgconfig(poppler-qt5)
rundeps    :
    - texlive
setup      : |
    %cmake -DDESIRED_QT_VERSION=5 \
           -DTeXworks_DIC_DIR=/usr/share/hunspell \
           .
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
