name       : texworks
version    : 0.6.5
release    : 15
source     :
    - https://github.com/TeXworks/texworks/archive/refs/tags/release-0.6.5.tar.gz : d538eb32fc8e7373dddb95d4c118eee848ef7e9ca7b83fe346120971f259eed8
homepage   : https://www.tug.org/texworks/
license    : GPL-2.0-or-later
component  : editor
summary    : A simple TeX front-end program
description: |
    TeXworks is an environment for authoring TeX (LaTeX, ConTeXt, etc) documents, with a Unicode-based, TeX-aware editor, integrated PDF viewer, and a clean, simple interface accessible to casual and non-technical users.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Script)
    - pkgconfig(dbus-1)
    - pkgconfig(hunspell)
    - pkgconfig(poppler-qt5)
rundeps    :
    - texlive
setup      : |
    %patch -p1 < $pkgfiles/fix-compilation-with-qt-5-15.patch
    %cmake -DDESIRED_QT_VERSION=5 \
           -DTeXworks_DIC_DIR=/usr/share/hunspell \
           .
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
