name       : texworks
version    : 0.6.0
release    : 1
source     :
    - https://github.com/TeXworks/texworks/archive/release-0.6.0.tar.gz : abb0dd76fe8870d0caa83f8f98743b44b6d5ce6e4df406e47eb6d0ffc2559f7b
license    : GPL-2.0
component  : editor
summary    : A simple TeX front-end program
description: |
    A simple TeX front-end program
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(hunspell)
    - pkgconfig(poppler)
    - pkgconfig(poppler-qt4)
    - pkgconfig(QtCore)
setup      : |
    ln -s /usr/bin/moc-qt4 /usr/bin/moc
    ln -s /usr/bin/rcc-qt4 /usr/bin/rcc
    ln -s /usr/bin/uic-qt4 /usr/bin/uic
    %cmake .
build      : |
    %make
install    : |
    %make_install
