name       : texworks
version    : 0.6.1
release    : 3
source     :
    - https://github.com/TeXworks/texworks/archive/release-0.6.1.tar.gz : 6b8ed503633f18d04086002d837b5c306b0bffbf548161c803d287bc6a6446ae
license    : GPL-2.0
component  : editor
summary    : A simple TeX front-end program
description: |
    A simple TeX front-end program
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(hunspell)
    - pkgconfig(poppler)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Core)
rundeps    :
    - texlive
setup      : |
    %cmake -DDESIRED_QT_VERSION=5 .
build      : |
    %make
install    : |
    %make_install
